import { ArrowRight, CheckCircle2, ChevronLeft, Lightbulb, Mic, RotateCcw, Send, Square, Volume2, X } from 'lucide-react'
import { FormEvent, useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { Button } from '../components/ui'
import { scenarioById, scenarios } from '../data/scenarios'
import { ScenarioEngine, findNode } from '../engine/conversation'
import { useSpeechRecognition, useSpeechSynthesis } from '../hooks/useSpeech'
import { useAppStore } from '../store/useAppStore'
import type { ConversationFeedback } from '../types'
import { toLocalDateKey } from '../engine/daily'
import { useActiveSeconds } from '../hooks/useActiveSeconds'

export function ConversationSessionPage(){
  const [params]=useSearchParams();const navigate=useNavigate();const profile=useAppStore(s=>s.profile);const saveConversation=useAppStore(s=>s.saveConversation);const logActivity=useAppStore(s=>s.logActivity);const dailySessions=useAppStore(s=>s.dailySessions);const completeDailyTask=useAppStore(s=>s.completeDailyTask)
  const scenario=scenarioById.get(params.get('id')??'')??scenarios[0];const engine=useMemo(()=>new ScenarioEngine(),[]);const [session,setSession]=useState(()=>engine.startSession(scenario));const [text,setText]=useState('');const [feedback,setFeedback]=useState<ConversationFeedback|null>(null);const [showHints,setShowHints]=useState(false);const [hintsUsed,setHintsUsed]=useState(0);const [saving,setSaving]=useState(false);const readActiveSeconds=useActiveSeconds()
  const node=findNode(scenario,session.currentNodeId);const speech=useSpeechSynthesis(profile?.voiceRate??.9);const recognition=useSpeechRecognition(setText)
  const submit=(event?:FormEvent)=>{event?.preventDefault();if(!text.trim()||!node)return;recognition.cancel();const result=engine.sendMessage(session,scenario,text.trim());setSession(result.session);setFeedback(result.feedback);setText('');setShowHints(false)}
  const finish=async()=>{setSaving(true);const now=new Date();const final=engine.endSession(session);const toSave=profile?.saveConversationText===false?{...final,messages:[]}:final;await saveConversation(toSave);const duration=readActiveSeconds();const attempts=session.messages.filter(message=>message.role==='user').length;const localDate=toLocalDateKey(now);await Promise.all(['listening','speaking'].map(skill=>logActivity({id:`${final.id}-conversation-${skill}`,localDate,contentId:scenario.id,type:'conversation',skill:skill as 'listening'|'speaking',durationSeconds:Math.round(duration/2),attempts,hintsUsed,correct:session.completedNodes.length>=scenario.nodes.length,createdAt:now.toISOString()})));const daily=dailySessions.find(item=>item.id===localDate);const task=daily?.tasks.find(item=>item.kind==='conversation');if(daily&&task)await completeDailyTask(daily.id,task.id,now);navigate('/conversation')}
  return <div className="flex min-h-dvh flex-col bg-conversation text-white">
    <header className="safe-top flex items-center gap-3 border-b border-white/10 bg-conversation/95 px-4 pb-4 backdrop-blur"><button aria-label="회화 종료" onClick={()=>{recognition.cancel();navigate('/conversation')}} className="flex h-11 w-11 items-center justify-center rounded-xl hover:bg-white/10"><ChevronLeft/></button><div className="min-w-0 flex-1"><p className="truncate font-bold">{scenario.title}</p><p className="text-xs text-slate-400">{scenario.category} · {session.completedNodes.length}/{scenario.nodes.length}턴</p></div><span className="rounded-full bg-blue-500/20 px-3 py-1 text-xs font-bold text-blue-300">시나리오</span></header>
    <main className="mx-auto flex w-full max-w-2xl flex-1 flex-col px-4 pb-[max(20px,env(safe-area-inset-bottom))]">
      <div className="flex-1 space-y-5 overflow-y-auto py-6">{session.messages.map((message,index)=><div key={`${index}-${message.english}`} className={`flex ${message.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[88%] rounded-3xl px-5 py-4 ${message.role==='user'?'rounded-br-md bg-blue-500':'rounded-bl-md bg-surface'}`}><p className="leading-7">{message.english}</p>{message.korean&&<p className="mt-2 text-sm text-slate-400">{message.korean}</p>}{message.role==='tutor'&&index===session.messages.length-1&&<button aria-label="튜터 문장 듣기" onClick={()=>speech.speak(message.english)} className="mt-3 flex min-h-10 items-center gap-2 text-xs font-bold text-blue-300"><Volume2 size={16}/>{speech.speaking?'재생 중':'듣기'}</button>}</div></div>)}
        {feedback&&<div className={`rounded-2xl border p-4 text-sm ${feedback.status==='matched'?'border-emerald-400/30 bg-emerald-400/10':'border-amber-400/30 bg-amber-400/10'}`}><div className="flex gap-2"><CheckCircle2 className={feedback.status==='matched'?'text-emerald-400':'text-amber-400'} size={18}/><div><b>{feedback.status==='matched'?'의도를 이해했어요':'다시 확인해 볼까요?'}</b><p className="mt-1 leading-6 text-slate-300">{feedback.message}</p>{feedback.naturalAlternative&&<p className="mt-2 text-blue-200">더 자연스럽게: {feedback.naturalAlternative}</p>}{feedback.politeAlternative&&<p className="mt-1 text-blue-200">더 공손하게: {feedback.politeAlternative}</p>}</div></div></div>}
        {!session.currentNodeId&&<div className="rounded-3xl bg-white p-6 text-center text-ink"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-green-100 text-green-700"><CheckCircle2 size={28}/></div><h2 className="mt-4 text-2xl font-bold">대화 완료!</h2><p className="mt-2 text-sm leading-6 text-muted">{engine.getFeedback(session)}<br/>{session.savedExpressionIds.length}개 표현이 복습 후보로 선택됐어요.</p><Button className="mt-6 w-full" disabled={saving} onClick={finish}>기록 저장하고 마치기 <ArrowRight size={18}/></Button></div>}
      </div>
      {node&&<div className="sticky bottom-0 rounded-3xl border border-white/10 bg-surface p-3 shadow-2xl"><button onClick={()=>{if(!showHints)setHintsUsed(value=>value+1);setShowHints(!showHints)}} className="mb-2 flex min-h-10 items-center gap-2 px-2 text-xs font-bold text-blue-300"><Lightbulb size={16}/>{showHints?'힌트 닫기':'힌트 보기'}</button>{showHints&&<div className="mb-3 rounded-2xl bg-conversation/60 p-3 text-xs leading-5 text-slate-300"><p>{node.hints[0]}</p><p className="mt-2 text-blue-200">예: {node.suggestedAnswers[0]}</p></div>}
        {recognition.listening&&<div aria-live="polite" className="mb-3 rounded-xl bg-blue-400/10 px-3 py-2 text-xs text-blue-200"><b>중간 인식</b><p className="mt-1">{recognition.interimTranscript||'말씀해 주세요…'}</p></div>}{recognition.error&&<p role="alert" className="mb-3 rounded-xl bg-amber-400/10 px-3 py-2 text-xs text-amber-200">{recognition.error}</p>}
        <form onSubmit={submit} className="flex items-end gap-2">{recognition.listening?<><button type="button" aria-label="말하기 완료" onClick={recognition.stop} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-blue-500 text-white"><Square size={18}/></button><button type="button" aria-label="음성 인식 취소" onClick={recognition.cancel} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white/10 text-slate-300"><X size={18}/></button></>:<button type="button" aria-label="음성으로 답하기" disabled={!recognition.supported} onClick={recognition.start} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white/10 text-blue-300 disabled:opacity-40"><Mic size={20}/></button>}<textarea aria-label="영어 답변" rows={1} value={text} onChange={e=>setText(e.target.value)} placeholder="영어로 답해 보세요" className="min-h-12 flex-1 resize-none rounded-2xl border border-white/10 bg-conversation px-4 py-3 text-sm text-white placeholder:text-slate-500 focus:border-blue-400"/><button aria-label="답변 보내기" disabled={recognition.listening||!text.trim()} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-blue-500 disabled:opacity-40"><Send size={19}/></button></form>{(recognition.finalTranscript||recognition.error)&&<button onClick={recognition.retry} className="mt-2 flex min-h-10 items-center gap-2 px-2 text-xs font-bold text-blue-300"><RotateCcw size={15}/> 다시 말하기</button>}
        <p className="mt-2 px-2 text-[10px] leading-4 text-slate-500">음성 인식은 지원 브라우저에서만 제공되며 정밀 발음 평가가 아닙니다. 텍스트 입력은 항상 사용할 수 있습니다.</p>
      </div>}
    </main>
  </div>
}
