import { ArrowLeft, ArrowRight, Check, Headphones, Mic2, RotateCcw, Volume2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { Button, Progress } from '../components/ui'
import { expressions, expressionById } from '../data/expressions'
import { useSpeechRecognition, useSpeechSynthesis } from '../hooks/useSpeech'
import { useAppStore } from '../store/useAppStore'
import { toLocalDateKey } from '../engine/daily'

const steps=['표현 이해','발음 듣기','따라 말하기','예문 이해','문장 만들기','정답 확인','복습 등록']
function shuffle<T>(items:T[]){return [...items].sort(()=>Math.random()-.5)}

export function LearningSessionPage(){
  const navigate=useNavigate();const [params]=useSearchParams();const records=useAppStore(s=>s.learningRecords);const profile=useAppStore(s=>s.profile);const complete=useAppStore(s=>s.completeLearning);const dailySessions=useAppStore(s=>s.dailySessions);const completeDailyTask=useAppStore(s=>s.completeDailyTask)
  const selected=expressionById.get(params.get('id')??'')??expressions.find(x=>!records.some(r=>r.expressionId===x.id))??expressions[0]
  const [step,setStep]=useState(0);const [input,setInput]=useState('');const [selectedAnswer,setSelectedAnswer]=useState<string|null>(null);const [checked,setChecked]=useState(false);const [saving,setSaving]=useState(false)
  const speech=useSpeechSynthesis(profile?.voiceRate??.9);const recognition=useSpeechRecognition(setInput)
  const options=useMemo(()=>shuffle([selected.english,...expressions.filter(x=>x.id!==selected.id).slice(0,3).map(x=>x.english)]),[selected.id])
  const correct=selectedAnswer===selected.english
  const next=async()=>{if(step<6){setStep(step+1);return}setSaving(true);const now=new Date();await complete({expressionId:selected.id,learnedAt:now.toISOString(),completedSteps:7,quizCorrect:correct,mode:'general',skillsPracticed:selected.skills});const daily=dailySessions.find(item=>item.id===toLocalDateKey(now));const task=daily?.tasks.find(item=>item.kind==='foundation');if(daily&&task)await completeDailyTask(daily.id,task.id,now);navigate('/learn',{replace:true})}
  return <div className="min-h-dvh bg-white pb-[max(24px,env(safe-area-inset-bottom))]">
    <header className="safe-top sticky top-0 z-20 flex items-center gap-3 border-b border-line bg-white/95 px-4 pb-4 backdrop-blur"><button aria-label="학습 종료" onClick={()=>navigate('/learn')} className="flex h-11 w-11 items-center justify-center rounded-xl hover:bg-slate-100"><X/></button><div className="flex-1"><Progress value={(step+1)/7*100}/></div><span className="text-xs font-bold text-muted">{step+1}/7</span></header>
    <main className="mx-auto flex min-h-[calc(100dvh-78px)] max-w-xl flex-col px-5 pt-8">
      <p className="text-xs font-bold uppercase tracking-[.16em] text-primary">STEP {step+1} · {steps[step]}</p>
      {step===0&&<section className="mt-8"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-muted">{selected.category} · {selected.level}</span><h1 className="mt-5 text-4xl font-bold leading-tight tracking-tight">{selected.english}</h1><p className="mt-4 text-xl text-muted">{selected.korean}</p><div className="mt-8 rounded-3xl bg-canvas p-5"><p className="text-sm font-bold">이 표현을 이렇게 써요</p><p className="mt-3 leading-7">{selected.example}</p><p className="mt-1 text-sm text-muted">{selected.exampleKorean}</p></div></section>}
      {step===1&&<section className="mt-10 text-center"><button onClick={()=>speech.speaking?speech.stop():speech.speak(selected.practiceSentence)} className={`mx-auto flex h-28 w-28 items-center justify-center rounded-full ${speech.speaking?'animate-pulse bg-blue-200 text-primary':'bg-primary text-white'} shadow-soft`}><Volume2 size={40}/></button><h1 className="mt-8 text-3xl font-bold">{selected.practiceSentence}</h1><p className="mt-3 text-muted">버튼을 눌러 여러 번 들어보세요.</p>{!speech.supported&&<p role="alert" className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-800">이 브라우저는 음성 재생을 지원하지 않습니다.</p>}{speech.supported&&!speech.voices.length&&<p className="mt-5 text-xs text-muted">기기에서 영어 음성을 불러오는 중이거나 사용할 수 없습니다. 음성 제공 방식은 기기별로 다릅니다.</p>}<Button variant="secondary" className="mt-6" onClick={()=>speech.speak(selected.practiceSentence)}><RotateCcw size={18}/> 다시 듣기</Button></section>}
      {step===2&&<section className="mt-8"><h1 className="text-3xl font-bold">듣고 따라 말해 보세요</h1><p className="mt-4 rounded-2xl bg-blue-50 p-5 text-xl font-semibold text-primary">{selected.practiceSentence}</p><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="말하거나 영어 문장을 입력하세요" className="mt-6 min-h-28 w-full resize-none rounded-2xl border border-line p-4 focus:border-primary"/><div className="mt-3 flex gap-3"><Button variant="secondary" onClick={()=>speech.speak(selected.practiceSentence)}><Headphones size={18}/> 듣기</Button><Button variant="secondary" disabled={!recognition.supported||recognition.listening} onClick={recognition.start}><Mic2 size={18}/>{recognition.listening?'듣는 중…':'말하기'}</Button></div>{recognition.error&&<p role="alert" className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-800">{recognition.error}</p>}<p className="mt-4 text-xs leading-5 text-muted">음성 인식 결과는 발음 정확도 점수가 아닙니다. 일부 브라우저에서는 온라인 음성 서비스를 사용할 수 있습니다.</p></section>}
      {step===3&&<section className="mt-8"><h1 className="text-3xl font-bold">문장 속에서 이해해요</h1><div className="mt-8 rounded-3xl border border-line p-6"><p className="text-xl font-bold leading-8">{selected.example}</p><div className="my-5 h-px bg-line"/><p className="leading-7 text-muted">{selected.exampleKorean}</p></div><div className="mt-5 flex flex-wrap gap-2">{selected.tags.map(tag=><span key={tag} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold">#{tag}</span>)}</div></section>}
      {step===4&&<section className="mt-8"><h1 className="text-3xl font-bold">뜻에 맞는 문장을 고르세요</h1><p className="mt-3 text-lg text-muted">“{selected.korean}”</p><div className="mt-7 space-y-3">{options.map(option=><button key={option} onClick={()=>setSelectedAnswer(option)} className={`min-h-16 w-full rounded-2xl border p-4 text-left font-semibold transition ${selectedAnswer===option?'border-primary bg-blue-50 text-primary':'border-line hover:bg-slate-50'}`}>{option}</button>)}</div></section>}
      {step===5&&<section className="mt-10 text-center">{!checked?<><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-blue-50 text-primary"><Check size={34}/></div><h1 className="mt-6 text-3xl font-bold">선택을 확인할까요?</h1><p className="mt-3 text-muted">정답을 확인하면 복습 일정에 자동으로 등록됩니다.</p><Button className="mt-8 w-full" disabled={!selectedAnswer} onClick={()=>setChecked(true)}>정답 확인</Button></>:<><div className={`mx-auto flex h-20 w-20 items-center justify-center rounded-full ${correct?'bg-green-100 text-green-700':'bg-red-100 text-red-700'}`}>{correct?<Check size={34}/>:<X size={34}/>}</div><h1 className="mt-6 text-3xl font-bold">{correct?'정답이에요!':'한 번 더 기억해요'}</h1><p className="mt-4 text-lg font-semibold">{selected.english}</p><p className="mt-2 text-muted">{selected.korean}</p></>}</section>}
      {step===6&&<section className="mt-10 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-3xl bg-violet-100 text-violet-700"><RotateCcw size={34}/></div><h1 className="mt-6 text-3xl font-bold">복습 준비 완료</h1><p className="mt-3 leading-6 text-muted">이 표현은 내일 첫 복습으로 등록됩니다.<br/>복습 결과에 따라 다음 일정이 조정돼요.</p><div className="mt-8 rounded-3xl bg-canvas p-5 text-left"><b>오늘 익힌 표현</b><p className="mt-2 text-lg text-primary">{selected.english}</p></div></section>}
      <div className="mt-auto flex gap-3 pt-10">{step>0&&<Button variant="secondary" aria-label="이전 단계" onClick={()=>setStep(step-1)}><ArrowLeft size={18}/></Button>}<Button className="flex-1" onClick={next} disabled={(step===4&&!selectedAnswer)||(step===5&&!checked)||saving}>{step===6?'학습 완료': '다음 단계'}<ArrowRight size={18}/></Button></div>
    </main>
  </div>
}
