import { Download, Flame, History, RotateCcw, Settings2, Trash2, Upload, UserRound } from 'lucide-react'
import { ChangeEvent, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, PageHeader } from '../components/ui'
import { useAppStore } from '../store/useAppStore'
import type { AppBackup, DailyGoal, Level } from '../types'
import { analyzeSkills, recommendTomorrow } from '../engine/analytics'
import { skillLabels } from '../data/learningPath'

export function MyPage(){
  const navigate=useNavigate();const inputRef=useRef<HTMLInputElement>(null);const profile=useAppStore(s=>s.profile)!;const learning=useAppStore(s=>s.learningRecords);const reviews=useAppStore(s=>s.reviews);const conversations=useAppStore(s=>s.conversations);const activities=useAppStore(s=>s.activities);const sessions=useAppStore(s=>s.dailySessions);const saveProfile=useAppStore(s=>s.saveProfile);const changeDailyGoal=useAppStore(s=>s.changeDailyGoal);const exportData=useAppStore(s=>s.exportData);const importData=useAppStore(s=>s.importData);const resetData=useAppStore(s=>s.resetData)
  const [message,setMessage]=useState('');const uniqueDays=new Set([...learning.map(x=>x.learnedAt.slice(0,10)),...conversations.map(x=>x.startedAt.slice(0,10)),...sessions.map(x=>x.localDate)]).size
  const insights=analyzeSkills(activities);const recommendation=recommendTomorrow(activities)
  const stats=[{value:uniqueDays,label:'총 학습 일수',Icon:Flame},{value:learning.length,label:'완료 학습',Icon:History},{value:reviews.length,label:'학습 표현',Icon:RotateCcw},{value:conversations.filter(x=>x.completedAt).length,label:'완료 회화',Icon:Settings2}]
  const patchProfile=(patch:Partial<typeof profile>)=>saveProfile({...profile,...patch})
  const download=()=>{const blob=new Blob([JSON.stringify(exportData(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`naro-backup-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);setMessage('백업 파일을 저장했습니다.')}
  const restore=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()) as AppBackup;if(!confirm('현재 데이터를 백업 파일로 교체할까요?'))return;await importData(parsed);setMessage('백업을 복원했습니다.')}catch{setMessage('올바른 NARO 백업 파일이 아닙니다.')}finally{event.target.value=''}}
  const reset=async()=>{if(!confirm('모든 학습 기록과 설정을 이 기기에서 삭제할까요? 이 작업은 되돌릴 수 없습니다.'))return;await resetData();navigate('/onboarding',{replace:true})}
  return <><PageHeader eyebrow="MY" title="나의 학습" description="실제 이 기기에 저장된 기록만 보여드려요." action={<div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-primary"><UserRound/></div>}/><div className="space-y-5 px-5 sm:px-8">
    {message&&<div role="status" className="rounded-2xl bg-blue-50 p-4 text-sm font-semibold text-blue-800">{message}</div>}
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{stats.map(({value,label,Icon})=><div key={label} className="rounded-2xl border border-line bg-white p-4"><Icon className="text-primary" size={20}/><b className="mt-3 block text-2xl">{value}</b><span className="text-xs text-muted">{label}</span></div>)}</section>
    <section className="overflow-hidden rounded-3xl border border-line bg-white"><h2 className="border-b border-line p-5 text-lg font-bold">학습 설정</h2><label className="flex items-center justify-between gap-4 border-b border-line p-5"><span><b className="block text-sm">현재 수준</b><small className="text-muted">자가 선택 수준</small></span><select value={profile.level} onChange={e=>patchProfile({level:e.target.value as Level})} className="min-h-11 rounded-xl border border-line bg-white px-3 text-sm font-semibold">{['왕초보','초급','초중급','중급'].map(x=><option key={x}>{x}</option>)}</select></label><label className="flex items-center justify-between gap-4 border-b border-line p-5"><span><b className="block text-sm">하루 목표</b><small className="text-muted">Daily 훈련 목표 시간</small></span><select value={profile.dailyGoal} onChange={e=>void changeDailyGoal(Number(e.target.value) as DailyGoal)} className="min-h-11 rounded-xl border border-line bg-white px-3 text-sm font-semibold">{(![15,30,45,60,90].includes(profile.dailyGoal)?[profile.dailyGoal]:[]).concat([15,30,45,60,90]).map(x=><option key={x} value={x}>{x}분</option>)}</select></label><label className="block p-5"><span className="flex justify-between text-sm font-bold"><span>음성 재생 속도</span><span>{profile.voiceRate.toFixed(1)}×</span></span><input aria-label="음성 재생 속도" type="range" min="0.6" max="1.2" step="0.1" value={profile.voiceRate} onChange={e=>patchProfile({voiceRate:Number(e.target.value)})} className="mt-4 w-full accent-primary"/></label><label className="flex items-center justify-between border-t border-line p-5"><span><b className="block text-sm">회화 문장 저장</b><small className="text-muted">끄면 이후 세션의 대화문은 저장하지 않음</small></span><input type="checkbox" checked={profile.saveConversationText} onChange={e=>patchProfile({saveConversationText:e.target.checked})} className="h-6 w-6 accent-primary"/></label></section>
    <section className="rounded-3xl border border-line bg-white p-5"><h2 className="text-lg font-bold">4영역 활동 기록</h2><p className="mt-2 text-sm text-muted">활동량은 공인 실력 점수가 아닙니다. 정답·재시도·힌트 기록으로 다음 연습 비중만 추천합니다.</p><div className="mt-5 space-y-3">{insights.map(item=><div key={item.skill} className="flex items-center justify-between rounded-2xl bg-canvas p-3"><div><b className="text-sm">{skillLabels[item.skill]}</b><p className="text-xs text-muted">{item.activities}회 · {Math.floor(item.seconds/60)}분 · 재시도 {item.retries}</p></div><span className="text-xs font-bold text-primary">{item.accuracy===null?'기록 대기':`${Math.round(item.accuracy*100)}%`}</span></div>)}</div><div className="mt-4 rounded-2xl bg-blue-50 p-4 text-sm text-blue-900"><b>다음 추천: {skillLabels[recommendation.focus]}</b><p className="mt-1 text-xs leading-5">{recommendation.message} 초급 단계에서는 다른 세 영역도 계속 포함합니다.</p></div></section>
    <section className="rounded-3xl border border-line bg-white p-5"><h2 className="text-lg font-bold">내 데이터</h2><p className="mt-2 text-sm leading-6 text-muted">기기 변경 시 자동 동기화되지 않습니다. JSON 백업 파일에는 학습 기록과 저장한 대화가 포함될 수 있으니 안전하게 보관하세요.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Button variant="secondary" onClick={download}><Download size={18}/> JSON 백업</Button><Button variant="secondary" onClick={()=>inputRef.current?.click()}><Upload size={18}/> 백업 복원</Button><input ref={inputRef} type="file" accept="application/json,.json" className="hidden" onChange={restore}/></div></section>
    <Button variant="danger" className="w-full" onClick={reset}><Trash2 size={18}/> 모든 로컬 데이터 초기화</Button><p className="pb-4 text-center text-xs leading-5 text-muted">NARO는 별도 서버 없이 작동합니다.<br/>음성 기능의 처리 방식과 인터넷 요구 여부는 브라우저 및 운영체제에 따라 다를 수 있습니다.</p>
  </div></>
}
