import { ArrowLeft, ArrowRight, Check, Eye, Headphones, Mic2, RotateCcw, Volume2 } from 'lucide-react'
import { useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, Progress } from '../components/ui'
import { expressions } from '../data/expressions'
import { normalize } from '../engine/conversation'
import { toLocalDateKey } from '../engine/daily'
import { useSpeechRecognition, useSpeechSynthesis } from '../hooks/useSpeech'
import { useActiveSeconds } from '../hooks/useActiveSeconds'
import { useAppStore } from '../store/useAppStore'
import type { ActivityType } from '../types'
import { speakingTrainingSteps } from '../data/speaking'

export function SpeakingTrainingPage(){
  const navigate=useNavigate();const profile=useAppStore(s=>s.profile);const learning=useAppStore(s=>s.learningRecords);const log=useAppStore(s=>s.logActivity);const sessions=useAppStore(s=>s.dailySessions);const complete=useAppStore(s=>s.completeDailyTask)
  const expression=expressions.find(item=>!learning.some(record=>record.expressionId===item.id))??expressions[0];const [step,setStep]=useState(0);const [input,setInput]=useState('');const [attempts,setAttempts]=useState(1);const [hint,setHint]=useState(false);const [selfCorrect,setSelfCorrect]=useState<boolean|null>(null);const trainingId=useRef(crypto.randomUUID());const readActiveSeconds=useActiveSeconds();const speech=useSpeechSynthesis(profile?.voiceRate??.9);const recognition=useSpeechRecognition(text=>{setInput(text);setAttempts(value=>value+1)})
  const today=toLocalDateKey();const daily=sessions.find(item=>item.id===today);const dailyTask=daily?.tasks.find(item=>item.kind==='shadowing')
  const record=async(type:ActivityType,correct?:boolean)=>{await log({id:`${trainingId.current}-${type}`,localDate:today,sessionId:daily?.id,taskId:dailyTask?.id,contentId:expression.id,type,skill:type==='listening'?'listening':'speaking',durationSeconds:readActiveSeconds(),attempts,hintsUsed:hint?1:0,correct,createdAt:new Date().toISOString()})}
  const next=async()=>{if(step===0)await record('listening');if(step===1)await record('speaking_repeat',selfCorrect??undefined);if(step===2){const target=new Set(normalize(expression.english).split(' ').filter(x=>x.length>2));const answer=new Set(normalize(input).split(' '));const correct=[...target].filter(x=>answer.has(x)).length>=Math.max(1,Math.ceil(target.size*.6));await record('speaking_recall',correct)}if(step===3){await record('speaking_respond',input.trim().split(/\s+/).length>=3);if(daily&&dailyTask)await complete(daily.id,dailyTask.id);return navigate('/daily')}setStep(value=>value+1);setInput('');setAttempts(1);setHint(false);setSelfCorrect(null)}
  return <div className="mx-auto flex min-h-dvh max-w-xl flex-col bg-white px-5 pb-[max(24px,env(safe-area-inset-bottom))] pt-[max(20px,env(safe-area-inset-top))]"><header className="flex items-center gap-3"><button aria-label="나가기" onClick={()=>navigate('/daily')} className="flex h-11 w-11 items-center justify-center rounded-xl hover:bg-slate-100"><ArrowLeft/></button><div className="flex-1"><Progress value={(step+1)*25}/></div><b className="text-xs text-muted">{step+1}/4</b></header><p className="mt-10 text-xs font-bold uppercase tracking-[.18em] text-primary">STEP {step+1} · {speakingTrainingSteps[step].label}</p>
    {step===0&&<section className="flex flex-1 flex-col items-center justify-center text-center"><button onClick={()=>speech.speak(expression.practiceSentence)} className={`flex h-28 w-28 items-center justify-center rounded-full ${speech.speaking?'animate-pulse bg-blue-200 text-primary':'bg-primary text-white'}`}><Volume2 size={42}/></button><h1 className="mt-8 text-3xl font-bold">먼저 소리에 집중하세요</h1><p className="mt-3 leading-6 text-muted">문장을 보지 않고 2–3번 들어 보세요.<br/>음성 품질과 온라인 처리 여부는 기기마다 다릅니다.</p><Button variant="secondary" className="mt-6" onClick={()=>speech.speak(expression.practiceSentence)}><RotateCcw size={18}/> 다시 듣기</Button></section>}
    {step===1&&<section className="mt-8"><h1 className="text-3xl font-bold">보고 따라 말하세요</h1><p className="mt-6 rounded-3xl bg-blue-50 p-6 text-2xl font-bold leading-9 text-primary">{expression.english}</p><div className="mt-5 flex gap-3"><Button variant="secondary" onClick={()=>speech.speak(expression.english)}><Headphones size={18}/> 듣기</Button><Button variant="secondary" disabled={!recognition.supported||recognition.listening} onClick={recognition.start}><Mic2 size={18}/> {recognition.listening?'듣는 중':'말하기'}</Button></div><textarea value={input} onChange={e=>setInput(e.target.value)} className="mt-4 min-h-24 w-full rounded-2xl border border-line p-4" placeholder="음성 인식 결과 또는 직접 입력"/><p className="mt-5 text-sm font-bold">문장을 끝까지 따라 했나요?</p><div className="mt-3 grid grid-cols-2 gap-3"><Button variant={selfCorrect===false?'danger':'secondary'} onClick={()=>setSelfCorrect(false)}>다시 연습</Button><Button variant={selfCorrect===true?'primary':'secondary'} onClick={()=>setSelfCorrect(true)}>따라 했어요</Button></div></section>}
    {step===2&&<section className="mt-8"><h1 className="text-3xl font-bold">영어 문장을 떠올리세요</h1><p className="mt-6 rounded-3xl bg-canvas p-6 text-xl font-bold">{expression.korean}</p>{hint&&<p className="mt-3 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">첫 단어: {expression.english.split(' ')[0]}</p>}<textarea value={input} onChange={e=>setInput(e.target.value)} className="mt-5 min-h-28 w-full rounded-2xl border border-line p-4" placeholder="영어로 말하거나 입력하세요"/><div className="mt-3 flex gap-3"><Button variant="secondary" onClick={()=>setHint(true)}><Eye size={18}/> 힌트</Button><Button variant="secondary" disabled={!recognition.supported||recognition.listening} onClick={recognition.start}><Mic2 size={18}/> 말하기</Button></div></section>}
    {step===3&&<section className="mt-8"><h1 className="text-3xl font-bold">내 답으로 대화하세요</h1><div className="mt-6 rounded-3xl bg-conversation p-6 text-white"><p className="text-xs font-bold text-blue-300">NARO TUTOR</p><p className="mt-3 text-xl font-bold">Please introduce yourself in one or two sentences.</p><p className="mt-2 text-sm text-slate-400">한두 문장으로 자신을 소개해 주세요.</p></div>{hint&&<p className="mt-3 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">예: Hello, I’m Mina. I’m from Korea.</p>}<textarea value={input} onChange={e=>setInput(e.target.value)} className="mt-5 min-h-28 w-full rounded-2xl border border-line p-4" placeholder="내 답변을 말하거나 입력하세요"/><div className="mt-3 flex gap-3"><Button variant="secondary" onClick={()=>setHint(true)}><Eye size={18}/> 예시</Button><Button variant="secondary" disabled={!recognition.supported||recognition.listening} onClick={recognition.start}><Mic2 size={18}/> 말하기</Button></div><p className="mt-4 text-xs leading-5 text-muted">음성 인식은 정밀 발음 평가가 아닙니다. 지원되지 않으면 텍스트와 자기 평가로 동일한 흐름을 완료할 수 있습니다.</p></section>}
    <Button className="mt-auto w-full" disabled={(step===1&&selfCorrect===null)||(step>=2&&!input.trim())} onClick={()=>void next()}>{step===3?<><Check size={18}/> 훈련 완료</>:<>다음 단계 <ArrowRight size={18}/></>}</Button>{recognition.error&&<p role="alert" className="mt-3 text-sm text-red-700">{recognition.error}</p>}</div>
}
